"""passive_deletes for role

Revision ID: 2f6f2234615b
Revises: 6f2899e4122d
Create Date: 2023-06-08 23:47:35.455570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6f2234615b'
down_revision = '6f2899e4122d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_history', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'auth_history', type_='unique')
    # ### end Alembic commands ###
